spring:
  # shardingjdbc 配置
  shardingsphere:
    datasource:
      names: shardingmaster,shardingslave0
      shardingmaster:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/datasource1
        username: root
        password: password
      shardingslave0:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/datasource1_slave
        username: root
        password: password
    masterslave:
      name: ms
      load-balance-algorithm-type: round_robin
      master-data-source-name: shardingmaster
      slave-data-source-names: shardingslave0
    props:
      sql:
        show: true
  # 动态数据源配置
  datasource:
    dynamic:
      primary: sharding
      datasource:
        slave:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://127.0.0.1:3306/datasource2
          username: root
          password: password

logging:
  level:
    root: info
    com.shenjies88.practice.datasource: debug
    org.springframework.jdbc: debug
