#spring:
#  datasource:
#    dynamic:
#      primary: datasource1 #设置默认的数据源或者数据源组,默认值即为master
#      strict: true #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
#      datasource:
#        datasource1:
#          url: jdbc:mysql://127.0.0.1:3306/datasource1
#          username: root
#          password: password
#        datasource2:
#          url: jdbc:mysql://127.0.0.1:3306/datasource2
#          username: root
#          password: password
spring:
  # shardingjdbc 配置
  shardingsphere:
    datasource:
      names: shardingmaster,shardingslave0
      shardingmaster:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://127.0.0.1:3306/datasource1
        username: root
        password: password
      shardingslave0:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://127.0.0.1:3306/datasource1_slave
        username: root
        password: password
    masterslave:
      name: ms
      load-balance-algorithm-type: round_robin
      master-data-source-name: shardingmaster
      slave-data-source-names: shardingslave0
    props:
      sql:
        show: true
  # 动态数据源配置
  datasource:
    dynamic:
      primary: sharding
      datasource:
        slave:
          url: jdbc:mysql://127.0.0.1:3306/datasource2
          username: root
          password: password

logging:
  level:
    root: info
    com.shenjies88.practice.datasource: debug
    org.springframework.jdbc: debug
